### ISSUE TITLE
I have a couple questions

### ISSUE THREAD

**Issue by Marvin-YYC** [tuxphone/CubeCellRepeater#7]
Thanks for sharing this code here! It worked GREAT!
I'm kind of new at coding and Meshtastic so I'm wondering about a couple things. While connected to PlatformIO I can see it receiving packets and retransmitting them and the LED lights flash accordingly. 
I realize it isn't currently supported by Meshtastic and won't function the same as other Meshtastic supported devices. 

That said,  I am not able to connect to the CubeCell via serial port to  the meshtastic web client,  and I can't use the Meshtastic app to connect it by serial to my smartphone either. Did I do something wrong, or is this normal?

Is there anyway to make the node visible to other nodes?  I now realize that repeaters do not appear in the nodes list, but if I could see my repeater I might be able to see it's telemetry, and check it's status, battery condition, etc.  

 Thank you

**Comment by tuxphone** [comment]
Hello Marvin, the CubeCell is not a working Meshtastic Node. 
It is a device to monitor MT traffic and/or to extend your network, using the CC as repeaters.

Not being a MT node means that it will not announce itself in the mesh. Right now it is not able to receive messages via serial and send them via lora. It just takes the LoRa packets, decrypt them if possible, posting the content to serial and repeats the packet.

The CubeCell hardware is very limited. It is more than sufficient for TTN but not for Meshtastic in the form of a functionung MT node.

**Comment by Marvin-YYC** [comment]
Hello tuxphone 
Thanks for getting back to me, and thanks again for the great code.
I think I will mount this on the roof with a solar panel and see how that works.
Really happy to have found a use for my CubeCell so it not collecting dust in a box :)

With the CC hardware limitations do you think it will ever be supported by Meshtastic and added to their hardware list?
